/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TripsIndexImport } from './routes/trips/index'
import { Route as ExploreIndexImport } from './routes/explore/index'
import { Route as AccountIndexImport } from './routes/account/index'
import { Route as FlightsHistoryImport } from './routes/flights/history'
import { Route as FlightsAddImport } from './routes/flights/add'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthForgotPasswordImport } from './routes/auth/forgot-password'
import { Route as AccountSettingsImport } from './routes/account/settings'
import { Route as AccountBillingImport } from './routes/account/billing'
import { Route as FlightsFlightIdIndexImport } from './routes/flights/$flightId/index'
import { Route as FlightsFlightIdEditImport } from './routes/flights/$flightId/edit'
import { Route as FlightsFlightIdAlternativesImport } from './routes/flights/$flightId/alternatives'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TripsIndexRoute = TripsIndexImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRoute,
} as any)

const ExploreIndexRoute = ExploreIndexImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRoute,
} as any)

const AccountIndexRoute = AccountIndexImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRoute,
} as any)

const FlightsHistoryRoute = FlightsHistoryImport.update({
  id: '/flights/history',
  path: '/flights/history',
  getParentRoute: () => rootRoute,
} as any)

const FlightsAddRoute = FlightsAddImport.update({
  id: '/flights/add',
  path: '/flights/add',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const AccountSettingsRoute = AccountSettingsImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRoute,
} as any)

const AccountBillingRoute = AccountBillingImport.update({
  id: '/account/billing',
  path: '/account/billing',
  getParentRoute: () => rootRoute,
} as any)

const FlightsFlightIdIndexRoute = FlightsFlightIdIndexImport.update({
  id: '/flights/$flightId/',
  path: '/flights/$flightId/',
  getParentRoute: () => rootRoute,
} as any)

const FlightsFlightIdEditRoute = FlightsFlightIdEditImport.update({
  id: '/flights/$flightId/edit',
  path: '/flights/$flightId/edit',
  getParentRoute: () => rootRoute,
} as any)

const FlightsFlightIdAlternativesRoute =
  FlightsFlightIdAlternativesImport.update({
    id: '/flights/$flightId/alternatives',
    path: '/flights/$flightId/alternatives',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/account/billing': {
      id: '/account/billing'
      path: '/account/billing'
      fullPath: '/account/billing'
      preLoaderRoute: typeof AccountBillingImport
      parentRoute: typeof rootRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsImport
      parentRoute: typeof rootRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/flights/add': {
      id: '/flights/add'
      path: '/flights/add'
      fullPath: '/flights/add'
      preLoaderRoute: typeof FlightsAddImport
      parentRoute: typeof rootRoute
    }
    '/flights/history': {
      id: '/flights/history'
      path: '/flights/history'
      fullPath: '/flights/history'
      preLoaderRoute: typeof FlightsHistoryImport
      parentRoute: typeof rootRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexImport
      parentRoute: typeof rootRoute
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreIndexImport
      parentRoute: typeof rootRoute
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsIndexImport
      parentRoute: typeof rootRoute
    }
    '/flights/$flightId/alternatives': {
      id: '/flights/$flightId/alternatives'
      path: '/flights/$flightId/alternatives'
      fullPath: '/flights/$flightId/alternatives'
      preLoaderRoute: typeof FlightsFlightIdAlternativesImport
      parentRoute: typeof rootRoute
    }
    '/flights/$flightId/edit': {
      id: '/flights/$flightId/edit'
      path: '/flights/$flightId/edit'
      fullPath: '/flights/$flightId/edit'
      preLoaderRoute: typeof FlightsFlightIdEditImport
      parentRoute: typeof rootRoute
    }
    '/flights/$flightId/': {
      id: '/flights/$flightId/'
      path: '/flights/$flightId'
      fullPath: '/flights/$flightId'
      preLoaderRoute: typeof FlightsFlightIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/settings': typeof AccountSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/flights/add': typeof FlightsAddRoute
  '/flights/history': typeof FlightsHistoryRoute
  '/account': typeof AccountIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/trips': typeof TripsIndexRoute
  '/flights/$flightId/alternatives': typeof FlightsFlightIdAlternativesRoute
  '/flights/$flightId/edit': typeof FlightsFlightIdEditRoute
  '/flights/$flightId': typeof FlightsFlightIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/settings': typeof AccountSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/flights/add': typeof FlightsAddRoute
  '/flights/history': typeof FlightsHistoryRoute
  '/account': typeof AccountIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/trips': typeof TripsIndexRoute
  '/flights/$flightId/alternatives': typeof FlightsFlightIdAlternativesRoute
  '/flights/$flightId/edit': typeof FlightsFlightIdEditRoute
  '/flights/$flightId': typeof FlightsFlightIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/settings': typeof AccountSettingsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/flights/add': typeof FlightsAddRoute
  '/flights/history': typeof FlightsHistoryRoute
  '/account/': typeof AccountIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/trips/': typeof TripsIndexRoute
  '/flights/$flightId/alternatives': typeof FlightsFlightIdAlternativesRoute
  '/flights/$flightId/edit': typeof FlightsFlightIdEditRoute
  '/flights/$flightId/': typeof FlightsFlightIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/billing'
    | '/account/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/flights/add'
    | '/flights/history'
    | '/account'
    | '/explore'
    | '/trips'
    | '/flights/$flightId/alternatives'
    | '/flights/$flightId/edit'
    | '/flights/$flightId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/billing'
    | '/account/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/flights/add'
    | '/flights/history'
    | '/account'
    | '/explore'
    | '/trips'
    | '/flights/$flightId/alternatives'
    | '/flights/$flightId/edit'
    | '/flights/$flightId'
  id:
    | '__root__'
    | '/'
    | '/account/billing'
    | '/account/settings'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/flights/add'
    | '/flights/history'
    | '/account/'
    | '/explore/'
    | '/trips/'
    | '/flights/$flightId/alternatives'
    | '/flights/$flightId/edit'
    | '/flights/$flightId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountBillingRoute: typeof AccountBillingRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  FlightsAddRoute: typeof FlightsAddRoute
  FlightsHistoryRoute: typeof FlightsHistoryRoute
  AccountIndexRoute: typeof AccountIndexRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  TripsIndexRoute: typeof TripsIndexRoute
  FlightsFlightIdAlternativesRoute: typeof FlightsFlightIdAlternativesRoute
  FlightsFlightIdEditRoute: typeof FlightsFlightIdEditRoute
  FlightsFlightIdIndexRoute: typeof FlightsFlightIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountBillingRoute: AccountBillingRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  FlightsAddRoute: FlightsAddRoute,
  FlightsHistoryRoute: FlightsHistoryRoute,
  AccountIndexRoute: AccountIndexRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  TripsIndexRoute: TripsIndexRoute,
  FlightsFlightIdAlternativesRoute: FlightsFlightIdAlternativesRoute,
  FlightsFlightIdEditRoute: FlightsFlightIdEditRoute,
  FlightsFlightIdIndexRoute: FlightsFlightIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/account/billing",
        "/account/settings",
        "/auth/forgot-password",
        "/auth/login",
        "/auth/signup",
        "/flights/add",
        "/flights/history",
        "/account/",
        "/explore/",
        "/trips/",
        "/flights/$flightId/alternatives",
        "/flights/$flightId/edit",
        "/flights/$flightId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/account/billing": {
      "filePath": "account/billing.tsx"
    },
    "/account/settings": {
      "filePath": "account/settings.tsx"
    },
    "/auth/forgot-password": {
      "filePath": "auth/forgot-password.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx"
    },
    "/flights/add": {
      "filePath": "flights/add.tsx"
    },
    "/flights/history": {
      "filePath": "flights/history.tsx"
    },
    "/account/": {
      "filePath": "account/index.tsx"
    },
    "/explore/": {
      "filePath": "explore/index.tsx"
    },
    "/trips/": {
      "filePath": "trips/index.tsx"
    },
    "/flights/$flightId/alternatives": {
      "filePath": "flights/$flightId/alternatives.tsx"
    },
    "/flights/$flightId/edit": {
      "filePath": "flights/$flightId/edit.tsx"
    },
    "/flights/$flightId/": {
      "filePath": "flights/$flightId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
